### ISSUE TITLE
关于归档和标签返回主页会打开新页面问题

### ISSUE THREAD

**Issue by list17** [Fechin/hexo-theme-diaspora#91]
URL:https://list17.top/
Description:
生成时候会在返回的时候加上`target="_blank"`导致返回失败
```html
    <div id="top">
        <a class="icon-left image-icon" href="javascript:history.back()" target="_blank" rel="noopener"></a>
    </div>
```
但是生成所用的代码是这样的
```ejs
 <div id="top">
        <a class="icon-left image-icon" href="javascript:history.back()"></a>
    </div>
```
在archive.ejs中

**Comment by list17** [comment]
问题已解决：
在hexo的config中将
```yml
external_link:
  enable: false # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
```
中enable设为false
